---
- name: deploy the ubuntu dev env basics
  hosts: localhost
  connection: local
  user: jefflangston
  sudo: true

  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - curl
        - sysstat
        - htop
        - git
        - neovim
        - tig
        - tmux
        - mosh
        - code
        - google-chrome-stable
        - openvpn
        - python-dev
        # - ruby-dev
        - postgresql
        - mysql-server
        - pandoc
        - xclip
        - wireshark
        - golang
        - wget
        - xpra
        - zsh

    - name: install ruby dependencies
      gem: name={{item}} state=present
      with_items:
        - bundler
        - rake

    - name: Install global python requirements
      pip: name={{item}} state=present
      with_items:
        - mycli
        - pgcli
        - neovim

    - name: setup zsh symlink
    file: path=~/.zshrc
          src=~/dotfiles/.zshrc
          state=link
          force=yes

    - name: Create file
      command: touch ~/.comp_zshrc
      args:
      creates: ~/.comp_zshrc

    - name: Install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    - name: Install n/ node.js
      shell: curl -L https://git.io/n-install | zsh -s -- -y

    - name: install yarn from npm
      npm: name={{item}} global=yes
      with_items:
        - yarn

    - name: install node/js dependencies
      yarn: name={{item}} global=yes
      with_items:
        - prettier
        - typescript

    - name: setup neovim symlink
    file: path=~/.config/nvim
          src=~/dotfiles/nvim
          state=link
          force=yes

    - name: setup tmux symlink
    file: path=~/.tmux.conf
          src=~/dotfiles/.tmux.conf
          state=link
          force=yes
    file: path=~/.tmuxline.conf
          src=~/dotfiles/.tmuxline.conf
          state=link
          force=yes

